FROM node:16.16

WORKDIR /usr/src/app

RUN apt-get update && apt-get install -y wget netcat-traditional && wget --version

# getting wait for
RUN wget -q -O /usr/bin/wait-for https://raw.githubusercontent.com/eficode/wait-for/v2.2.3/wait-for && \
    chmod +x /usr/bin/wait-for

# copying all from node folder to workdir folder (/usr/src/app)
COPY . .

EXPOSE 3000

RUN npm install

# CMD ["node", "src/index.js"]